/**
 * <copyright>
 * </copyright>
 *
 * $Id: VessieValidator.java,v 1.2 2008/05/26 13:48:28 scheerj Exp $
 */
package vessie.validation;


/**
 * A sample validator interface for {@link vessie.Vessie}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VessieValidator {
	boolean validate();

	boolean validateContenance(String value);

	boolean validateContenance(int value);

	boolean validateName(String value);
}
