/**
 * <copyright>
 * </copyright>
 *
 * $Id: AttributeCorrespondanceValidator.java,v 1.1 2008/05/26 07:05:10 scheerj Exp $
 */
package adaptor.validation;

import org.eclipse.emf.ecore.EAttribute;

/**
 * A sample validator interface for {@link adaptor.AttributeCorrespondance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeCorrespondanceValidator {
	boolean validate();

	boolean validateSrc(EAttribute value);
	boolean validateTarget(EAttribute value);
}
