/**
 * <copyright>
 * </copyright>
 *
 * $Id: InstanceValidator.java,v 1.6 2008/05/26 14:38:45 scheerj Exp $
 */
package adaptor.validation;

import org.eclipse.emf.ecore.EClass;

/**
 * A sample validator interface for {@link adaptor.Instance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InstanceValidator {
	boolean validate();

	boolean validateConcept(EClass value);

	boolean validateIsMain(boolean value);
}
