/**
 * <copyright>
 * </copyright>
 *
 * $Id: MatchingValidator.java,v 1.3 2008/05/26 09:25:12 scheerj Exp $
 */
package adaptor.validation;

import adaptor.CorrespondanceRule;
import adaptor.Instance;
import adaptor.LhsPattern;
import adaptor.RhsPattern;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link adaptor.Matching}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MatchingValidator {
	boolean validate();

	boolean validateCorrespondanceRule(EList<CorrespondanceRule> value);
	boolean validateComposed(EList<Instance> value);
	boolean validateLhs(LhsPattern value);
	boolean validateRhs(EList<RhsPattern> value);
}
