/**
 * <copyright>
 * </copyright>
 *
 * $Id: ProxyValidator.java,v 1.1 2008/05/16 09:05:06 scheerj Exp $
 */
package adaptor.validation;

import org.eclipse.emf.ecore.EClass;

/**
 * A sample validator interface for {@link adaptor.Proxy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProxyValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateType(EClass value);

	boolean validatePackage(String value);
}
