/**
 * <copyright>
 * </copyright>
 *
 * $Id: QueryValidator.java,v 1.2 2008/05/16 09:05:06 scheerj Exp $
 */
package adaptor.validation;

import adaptor.Proxy;
import adaptor.Request;

/**
 * A sample validator interface for {@link adaptor.Query}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface QueryValidator {
	boolean validate();

	boolean validateProxy(Proxy value);
	boolean validateRequest(Request value);
}
