/**
 * <copyright>
 * </copyright>
 *
 * $Id: RequestValidator.java,v 1.4 2008/05/26 14:38:45 scheerj Exp $
 */
package adaptor.validation;

import adaptor.Langage;

/**
 * A sample validator interface for {@link adaptor.Request}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RequestValidator {
	boolean validate();

	boolean validateExpression(String value);
	boolean validateLangage(Langage value);
}
