/**
 * <copyright>
 * </copyright>
 *
 * $Id: ColonneValidator.java,v 1.1 2008/06/03 13:28:42 scheerj Exp $
 */
package bdd.validation;

import bdd.Colonne;
import bdd.Table;

/**
 * A sample validator interface for {@link bdd.Colonne}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ColonneValidator {
	boolean validate();

	boolean validateIsPrimary(boolean value);
	boolean validateFk(Colonne value);
	boolean validateName(String value);

	boolean validateTable(Table value);
}
