/**
 * <copyright>
 * </copyright>
 *
 * $Id: TableValidator.java,v 1.1 2008/06/03 13:28:42 scheerj Exp $
 */
package bdd.validation;

import bdd.Colonne;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bdd.Table}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TableValidator {
	boolean validate();

	boolean validateS(EList<Colonne> value);
	boolean validateName(String value);
}
