/**
 * <copyright>
 * </copyright>
 *
 * $Id: ClasseValidator.java,v 1.1 2008/06/03 13:29:26 scheerj Exp $
 */
package objet.validation;

import objet.Propriete;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link objet.Classe}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClasseValidator {
	boolean validate();

	boolean validateA(EList<Propriete> value);
	boolean validateName(String value);
}
