/**
 * <copyright>
 * </copyright>
 *
 * $Id: RelationValidator.java,v 1.1 2008/06/03 13:29:26 scheerj Exp $
 */
package objet.validation;

import objet.Classe;

/**
 * A sample validator interface for {@link objet.Relation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelationValidator {
	boolean validate();

	boolean validateType(Classe value);
}
