/**
 * <copyright>
 * </copyright>
 *
 * $Id: LhsPatternValidator.java,v 1.3 2009/07/10 17:23:14 bcoppe Exp $
 */
package adaptor.validation;


/**
 * A sample validator interface for {@link adaptor.LhsPattern}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LhsPatternValidator {
	boolean validate();

}
