/**
 * <copyright>
 * </copyright>
 *
 * $Id: LanterneValidator.java,v 1.2 2008/06/04 11:50:10 scheerj Exp $
 */
package lanterne.validation;


/**
 * A sample validator interface for {@link lanterne.Lanterne}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LanterneValidator {
	boolean validate();

	boolean validateIntensite(int value);
	boolean validateLuminosite(String value);
}
